### ISSUE TITLE
Roadmap for a first public release

### ISSUE THREAD

**Issue by graste** [honeybee/honeybee#86]
Coarse grained road map:

- [x] tag current master as "legacy" or "0.5" or something and create a legacy branch if necessary for ongoing bug fixes
- [ ] decide what functionality belongs to the core lib and what is better placed in separate repositories (see [FriendsOfHoneybee/elasticsearch-v2](https://github.com/FriendsOfHoneybee/elasticsearch-v2)) as an example
- [x] Confirm license as MIT or MPL2
- [x] Rename `testing` dir to `tests`
- [x] Confirm minimum compatibility composer library versions and stability
- [x] Update out of date deps

This will then lead to stuff like

- more test coverage
- immutability all the things
- php7 all the things
- extract dataaccess stuff into separate repositories e.g FriendsOfHoneybee/elasticsearch-v5
- Honeybee home page and documentation

**Comment by MrHash** [comment]
Required adapters for 0.1 branch:
 - Elasticsearch2
 - Elasticsearch5
 - CouchDb
 - EventStore
 - Doctrine DBAL
 - RabbitMQ
