### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by MrHash** [honeybee/honeybee#88]
- [ ] remove task namespace and CRUD stuff
 - [ ] integrate immutable Trellis impl
 - [ ] integrate new Workflux impl
 - [ ] refactor AR and remove embedded entities
 - [ ] update command and event bus service registration

**Comment by MrHash** [comment]
Converted to project..
